package me.philippheuer.util.rest;

import com.jcabi.log.Logger;
import org.springframework.http.HttpRequest;
import org.springframework.http.client.ClientHttpRequestExecution;
import org.springframework.http.client.ClientHttpRequestInterceptor;
import org.springframework.http.client.ClientHttpResponse;

import java.io.IOException;

/**
 * Spring Rest: Logging Request Interceptor
 * <p>
 * The logging request interceptor can be applied to a {@link org.springframework.web.client.RestTemplate} and
 * will log the final request generated by all **previously** added interceptors.
 *
 * @author Philipp Heuer
 * @version %I%, %G%
 * @since 1.0
 */
public class LoggingRequestInterceptor implements ClientHttpRequestInterceptor {

	@Override
	public ClientHttpResponse intercept(HttpRequest request, byte[] body, ClientHttpRequestExecution execution) throws IOException {

		ClientHttpResponse response = execution.execute(request, body);

		log(request, body, response);

		return response;
	}

	private void log(HttpRequest request, byte[] body, ClientHttpResponse response) throws IOException {
		// do logging
		Logger.info(this, "Request: [ %s ][ %s ][ %s ][ %s ]", request.getURI(), request.getMethod(), request.getHeaders(), body.toString());
	}
}
