on:
  pull_request_target:
    types: [ opened ]
jobs:
  branch_check:
    runs-on: ubuntu-latest
    steps:
      - uses: vsoch/pull-request-action@1.0.13
        if: ${{ github.event.pull_request.base.ref != 'develop' }} # switch branch to develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: develop
  reviewer_assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2 # assign reviewer
        with:
          configuration-path: ".github/pr_review.yml"
  title_check:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3
        if: ${{ !['philippheuer', 'iprodigy', 'dependabot[bot]', 'dependabot-preview[bot]'].includes(github.event.pull_request.sender.login.toLowerCase()) }} # skip for maintainer and dependabot
        with:
          types: |
            feat
            fix
            deps
            build
            chore
            perf
            refactor
          requiredScope: false
          subjectPatternError: |
            Thank you for your contribiution. Unfortunate your title doesn't contain a proper title format.
            The title must be: `<type>: {title}`, when [`type`](https://twitch4j.github.io/docs/contributing/pull-request-guide#supported-types) **MUST** be defined in the sample title.
            For more details about sending pull request, please refer to our [documentation](https://twitch4j.github.io/docs/contributing/pull-request-guide)
